option(ENABLE_CLANG_TIDY "Enable static analysis with clang-tidy" ON)
option(ENABLE_INCLUDE_WHAT_YOU_USE "Enable static analysis with include-what-you-use" OFF)

if (ENABLE_CLANG_TIDY)
    find_program(CLANGTIDY clang-tidy-15)
    if (CLANGTIDY)
        set(CMAKE_CXX_CLANG_TIDY ${CLANGTIDY} -extra-arg=-Wno-unknown-warning-option -extra-arg=-std=c++2a)
    else ()
        message(SEND_ERROR "clang-tidy-12 requested but executable not found")
    endif ()
endif ()

if (ENABLE_INCLUDE_WHAT_YOU_USE)
    find_program(INCLUDE_WHAT_YOU_USE include-what-you-use)
    if (INCLUDE_WHAT_YOU_USE)
        set(CMAKE_CXX_INCLUDE_WHAT_YOU_USE ${INCLUDE_WHAT_YOU_USE})
    else ()
        message(SEND_ERROR "include-what-you-use requested but executable not found")
    endif ()
endif ()
