name: Build

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Install libc++-12
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 12
          apt-get install -y clang-format-12 libc++-12-dev libc++abi-12-dev

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.24.x'
 
      - name: Install Doxygen and dot
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Build with cmake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_BUILD_FAT_EXE=1 ..
          make

      - name: Run tests
        run: |
          cd build
          make test
